# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 763b738a31dc25b482e8d41cec1b4dfb89d4abc6442d36cce0aaa0e13f44be6dbca167028741fbf0249c92b227224058bbb433614e31a9eb389352492879b7b4

test:
  secret_key_base: 7b4d6a43f2684380bbbc45ccd6df869bc3df3b252b67119018d455a27a6fd795c0a6142d5a34b7a36603f78075091c400c8709004a0a4411f95bc5e54eb476c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
